### ISSUE TITLE
'Client' object has no attribute 'llm_tracker'

### ISSUE THREAD

**Issue by rmico77** [AgentOps-AI/agentops#291]
>>> # Criando as LLMs
>>> llama8=ChatGroq(model_name="llama3-8b-8192", api_key=GROQ_API_KEY)
>>> llama70=ChatGroq(model_name="llama3-70b-8192", api_key=GROQ_API_KEY)
>>> gpt3=ChatOpenAI(model="gpt-3.5-turbo", api_key=OPENAI_API_KEY)
>>>
>>>
>>> # Ferramenta de busca em PDF
>>> search_tool = PDFSearchTool(pdf=r'C:\Users\rmico\Desktop\CrewAI\Gilbert_Developmental_Biology_2019.pdf')
>>>
>>> # Agente de Leitura
>>> leitor = Agent(
...     role='Leitor Acadêmico',
...     goal='Extrair informações específicas do livro acadêmico em PDF',
...     backstory="Você é um leitor experiente em textos acadêmicos.",
...     tools=[search_tool],
...     verbose=True,
...     allow_delegation=False,
... )
🖇 AgentOps: Error: 'Client' object has no attribute 'llm_tracker'
2024-07-09 17:22:38,859 - 13680 - meta_client.py-meta_client:51 - WARNING: Error: 'Client' object has no attribute 'llm_tracker'
🖇 AgentOps: Failed to track an agent. This often happens if agentops.init() was not called before i nitializing an agent with the @track_agent decorator.
2024-07-09 17:22:38,908 - 13680 - agent.py-agent:23 - WARNING: Failed to track an agent. This often happens if agentops.init() was not called before initializing an agent with the @track_agent decorator.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rmico\AppData\Local\Programs\Python\Python312\Lib\site-packages\agentops\agent.py", line 25, in new_init
    logger.warning(
    ^^^^^^^
  File "C:\Users\rmico\AppData\Local\Programs\Python\Python312\Lib\site-packages\agentops\agent.py", line 19, in new_init
    original_init(self, *args, **kwargs)
  File "C:\Users\rmico\AppData\Local\Programs\Python\Python312\Lib\site-packages\crewai\agent.py", line 102, in __init__
    super().__init__(**config, **data)
  File "C:\Users\rmico\AppData\Local\Programs\Python\Python312\Lib\site-packages\crewai\agents\agent_builder\base_agent.py", line 128, in __init__
    super().__init__(**config, **data)
  File "C:\Users\rmico\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
  File "C:\Users\rmico\AppData\Local\Programs\Python\Python312\Lib\site-packages\crewai\agent.py", line 125, in set_agent_executor
    agentops.stop_instrumenting()
  File "C:\Users\rmico\AppData\Local\Programs\Python\Python312\Lib\site-packages\agentops\__init__.py", line 144, in stop_instrumenting

  File "C:\Users\rmico\AppData\Local\Programs\Python\Python312\Lib\site-packages\agentops\meta_client.py", line 56, in wrapper
    config = getattr(self, "config", None)
    ^^^^^^^
  File "C:\Users\rmico\AppData\Local\Programs\Python\Python312\Lib\site-packages\agentops\meta_client.py", line 49, in wrapper
    """Decorator within the metaclass to wrap method execution in try-except block."""
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rmico\AppData\Local\Programs\Python\Python312\Lib\site-packages\agentops\client.py", line 425, in stop_instrumenting
    token_cost_d = Decimal(0)
   ^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'llm_tracker'

**Comment by andkoma** [comment]
I could fix the error, when using on crewai by initialize the llm_tracker = None in the agentops\client.py _init_ function .
