### ISSUE TITLE
Runtime issue with Autogen + AgentOps

### ISSUE THREAD

**Issue by petekapakos** [AgentOps-AI/agentops#419]
## 🐛 Bug Report
I get the following error ~15% of the time when I run a process with Autogen.
Python 3.12
autogen 0.3.0
agentops 0.3.11

**🔎 Describe the Bug**
```
Exception in thread Thread-42 (_run):
Traceback (most recent call last):
  File "[...]\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "[...]\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "[...]\virtualenvs\[...]\Lib\site-packages\agentops\session.py", line 300, in _run
    self._flush_queue()
  File "[...]\virtualenvs\[...]\Lib\site-packages\agentops\session.py", line 279, in _flush_queue
    serialized_payload = safe_serialize(payload).encode("utf-8")
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]\virtualenvs\[...]\Lib\site-packages\agentops\helpers.py", line 91, in safe_serialize
    return json.dumps(cleaned_obj, default=default)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "[...]\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "[...]\virtualenvs\[...]\Lib\site-packages\agentops\helpers.py", line 65, in default
    return o.model_dump_json()
           ^^^^^^^^^^^^^^^^^^^
  File "[...]\virtualenvs\[...]\Lib\site-packages\pydantic\main.py", line 441, in model_dump_json
    return self.__pydantic_serializer__.to_json(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'method'>
```

**🔄 Reproduction Steps**
I have relatively simple code using a user proxy agent and an assistant agent

agentops.init()

user_proxy.initiate_chats(prompts)

**Comment by areibman** [comment]
We've pushed a fix to this-- update going out tomorrow!
